name: Build Passwall x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget python3

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

        git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
        git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages

        make defconfig

    - name: Build firmware
      run: |
        cd openwrt
        make menuconfig # 若你熟悉，可以改为自动选择
        make -j$(nproc)
